vimrc setup add vim and tmux

diff --git a/.bin/setup b/.bin/setup
--- a/.bin/setup
+++ b/.bin/setup
@@ -117,6 +117,8 @@ usage() {
                                                                                    
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 
+         vim                 Install/Updatee VIM
+         tmux                Install/Updatee TMUX
          alttab              Install Program Alttab - Same Windows Alt Tab
          anki                Install Program Anki
          arcicons            Install Gtk Dark-themes Icons
@@ -153,7 +155,6 @@ usage() {
          st                  Install Program St - Terminal
          sshbanner           Settings SSH Login Banner
          urxvt               Install Program URxvt - Terminal
-         vim                 Install Program Vim Version 8.2
          vifm                Install Program Vifm - Filebrowser
          weixin              Install Program Weixin - Linux Weixin
          yarn                Install Program Yarn
@@ -165,7 +166,106 @@ EOF
 }
 
 # ================================================================================================================================
-# TMUX 
+#
+#                                                              VIM 
+#
+# ================================================================================================================================
+
+Vim () {
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+
+    ROW
+    echo -e ""
+    echo -e "${YELLOW}VIM Is Being Installed${RESET}"
+    echo -e ""
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+
+# >>> REMOVE ALREADY EXISTS
+
+    if command -v vim >/dev/null 2>&1; then 
+        sudo apt remove -y --purge vi vim-tiny vim vim-runtime gvim vim-common vim-gui-common vim-nox > /dev/null 2>&1
+    fi
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+
+# >>> INSTALL DEPENDENCIES
+
+    echo -e "${MAGENTA}Install Dependencies${RESET}"
+    ${APT_INSTALL} libncurses5-dev python-dev python3-dev libwxgtk3.0-dev libgtk-3-dev > /dev/null 2>&1
+    ${APT_INSTALL} libatk1.0-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev > /dev/null 2>&1
+    if [ $? -eq 0 ]; then echo -e "${GREEN}[√] Successful${RESET}\n"; else echo -e "${RED}[X] Failed$2${RESET}\n"; fi
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+    
+# >>> PRETO BUILD
+
+    echo -e "${MAGENTA}Git Clone Or Update VIM${RESET}"
+    if [ -d "${SOURCE_DIR}/vim" ]; then 
+        cd ${SOURCE_DIR}/vim || return && git reset --hard > /dev/null 2>&1 && git pull > /dev/null 2>&1
+    else
+        $GIT_CLONE/vim/vim.git ${SOURCE_DIR}/vim 
+        cd ${SOURCE_DIR}/vim || return
+    fi
+    if [ $? -eq 0 ]; then echo -e "${GREEN}[√] Successful${RESET}\n"; else echo -e "${RED}[X] Failed$2${RESET}\n"; fi
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+
+# >>> START BUILD
+
+    echo -e "${MAGENTA}Start Build${RESET}"
+
+    (sudo ./configure --with-features=huge \
+        --enable-multibyte \
+        --enable-fontset \
+        --enable-rubyinterp \
+        --enable-pythoninterp \
+        --enable-python3interp \
+        --enable-luainterp \
+        --enable-cscope \
+        --enable-gui=auto \
+        --enable-perlinterp \
+        --enable-fontset \
+        # --with-python-config-dir=$(python2-config --configdir) \
+        --with-python3-config-dir=$(python3-config --configdir) \
+        --with-compiledby="TaoTao" \
+        --enable-largefile \
+        --with-x \
+        --enable-xim \
+        --enable-fontset \
+        --prefix=/usr/local) > /dev/null 2>&1 && \
+
+    sudo make > /dev/null 2>&1 && \
+    sudo make install > /dev/null 2>&1
+    if [ $? -eq 0 ]; then echo -e "${GREEN}[√] Successful${RESET}\n"; else echo -e "${RED}[X] Failed$2${RESET}\n"; fi
+
+    # --with-features=huge：支持最大特性
+    # --enable-rubyinterp：打开对 ruby 编写的插件的支持
+    # --enable-pythoninterp：打开对 python 编写的插件的支持
+    # --enable-python3interp：打开对 python3 编写的插件的支持
+    # --enable-luainterp：打开对 lua 编写的插件的支持
+    # --enable-perlinterp：打开对 perl 编写的插件的支持
+    # --enable-multibyte：打开多字节支持，可以在 Vim 中输入中文
+    # --enable-cscope：打开对cscope的支持
+    # --enable-gui=gtk3 表示生成采用 GNOME3 风格的 gvim
+    # --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ 指定 python 路径
+    # --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/ 指定 python3路径
+    # --prefix=/usr/local/vim：指定将要安装到的路径
+
+    echo -e "${BLUE}VIM Install Is Complete :: Version ${RESET} ${RED}$(vim --version | grep -o "VIM - Vi IMproved [0-9].[0-9]")${RESET} ";
+
+# --------------------------------------------------------------o----------------------------------------------------------------o
+    
+# >>> OUTPUT
+
+    ROW
+}
+
+# ================================================================================================================================
+#
+#                                                              TMUX 
+#
 # ================================================================================================================================
 
 Tmux() {
@@ -243,6 +343,7 @@ Tmux() {
     ROW
 
 }
+
 #---------------------------------------------------------------------------------------------------------------------------------------
 # Install Tools
 #---------------------------------------------------------------------------------------------------------------------------------------
@@ -1010,63 +1111,6 @@ I3gaps() {
 
 #---------------------------------------------------------------------------------------------------------------------------------------
 
-Vim () {
-
-    cd "$SOURCE_DIR" || return
-
-    if [ -d "vim" ]; then 
-        cd vim && git pull > /dev/null 2>&1
-    else
-        $GIT_CLONE/vim/vim && cd vim 
-    fi
-
-    sudo apt remove --purge vi vim-tiny vim vim-runtime gvim vim-common vim-gui-common vim-nox > /dev/null 2>&1
-    ${APT_INSTALL} libncurses5-dev python-dev python3-dev libwxgtk3.0-dev libgtk-3-dev > /dev/null 2>&1
-    ${APT_INSTALL} libatk1.0-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev > /dev/null 2>&1
-
-    (sudo ./configure --with-features=huge \
-        --enable-multibyte \
-        --enable-fontset \
-        --enable-rubyinterp \
-        --enable-pythoninterp \
-        --enable-python3interp \
-        --enable-luainterp \
-        --enable-cscope \
-        --enable-gui=auto \
-        --enable-perlinterp \
-        --enable-fontset \
-        # --with-python-config-dir=$(python2-config --configdir) \
-        --with-python3-config-dir=$(python3-config --configdir) \
-        --with-compiledby="TaoTao" \
-        --enable-largefile \
-        --with-x \
-        --enable-xim \
-        --enable-fontset \
-        --prefix=/usr/local) > /dev/null 2>&1 && \
-
-    sudo make > /dev/null 2>&1 && \
-    sudo make install > /dev/null 2>&1
-
-    # --with-features=huge：支持最大特性
-    # --enable-rubyinterp：打开对 ruby 编写的插件的支持
-    # --enable-pythoninterp：打开对 python 编写的插件的支持
-    # --enable-python3interp：打开对 python3 编写的插件的支持
-    # --enable-luainterp：打开对 lua 编写的插件的支持
-    # --enable-perlinterp：打开对 perl 编写的插件的支持
-    # --enable-multibyte：打开多字节支持，可以在 Vim 中输入中文
-    # --enable-cscope：打开对cscope的支持
-    # --enable-gui=gtk3 表示生成采用 GNOME3 风格的 gvim
-    # --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ 指定 python 路径
-    # --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/ 指定 python3路径
-    # --prefix=/usr/local/vim：指定将要安装到的路径
-
-    ROW
-    vim --version | grep -o "VIM - Vi IMproved [0-9].[0-9]"
-    ROW
-}
-
-#---------------------------------------------------------------------------------------------------------------------------------------
-
 Rofi() {
 
     cd "$SOURCE_DIR" || return
@@ -1104,6 +1148,12 @@ main() {
             usage
             exit 0
             ;;
+        vim)
+            Vim
+            ;;   
+        tmux)
+            Tmux
+            ;;   
         alttab)
             Alttab
             ;;
@@ -1220,9 +1270,6 @@ main() {
             ;;   
         i3gaps)
             I3gaps
-            ;;   
-        vim)
-            Vim
             ;;   
         rofi)
             Rofi
